### ISSUE TITLE
Add InChIKey lookup from cactus

### ISSUE THREAD

**Issue by jvansan** [mwang87/ChemicalStructureWebService#7]
It may be useful to add a feature which allows API users to try and lookup an InChIKey.

I implemented a very simple cactus lookup in a previous prototype:

```python
def cactus_inchikey_lookup(inchikey):
    url = "https://cactus.nci.nih.gov/chemical/structure/{0}/smiles".format(inchikey)
    r = requests.get(url)
    if r.ok:
        smiles = r.text.split()
        if smiles:
            return smiles[0]
    return None
```

This is a very simple/naive lookup, and could easily include a validation step using a regex.
Cactus also supports InChIKey lookup using the structure hash, so this feature should also be included.

**Comment by mwang87** [comment]
I agree, I think this would be useful. One thing that I think also could be useful and is totally feature creeping now and might be better served as a separate server now, is to provide a cache layer for classyfire. They just started throttling their throughput which puts a huge damper on some of the tools we have. 

For this I'll merge it in.

**Comment by mwang87** [comment]
The way I integrated this, is to convert the inchikey to both smiles, inchi, and mol. I added inchikey for another option in the inchi conversion api. I think thats a reasonable way to structure it.
